/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-07-17 18:11:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer.html", Long.valueOf(1752771139470L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Add Product</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\n");
      out.write("	");

	/* Checking the user credentials */
	String userType = (String) session.getAttribute("usertype");
	String userName = (String) session.getAttribute("username");
	String password = (String) session.getAttribute("password");

	if (userType == null || !userType.equals("admin")) {

		response.sendRedirect("login.jsp?message=Access Denied, Login as admin!!");

	}

	else if (userName == null || password == null) {

		response.sendRedirect("login.jsp?message=Session Expired, Login Again!!");

	}
	
      out.write('\n');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('	');

	String message = request.getParameter("message");
	
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row\"\n");
      out.write("			style=\"margin-top: 5px; margin-left: 2px; margin-right: 2px;\">\n");
      out.write("			<form action=\"./AddProductSrv\" method=\"post\"\n");
      out.write("				enctype=\"multipart/form-data\" class=\"col-md-6 col-md-offset-3\"\n");
      out.write("				style=\"border: 2px solid black; border-radius: 10px; background-color: #FFE5CC; padding: 10px;\">\n");
      out.write("				<div style=\"font-weight: bold;\" class=\"text-center\">\n");
      out.write("					<h2 style=\"color: green;\">Product Addition Form</h2>\n");
      out.write("					");

					if (message != null) {
					
      out.write("\n");
      out.write("					<p style=\"color: blue;\">\n");
      out.write("						");
      out.print(message);
      out.write("\n");
      out.write("					</p>\n");
      out.write("					");

					}
					
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div></div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6 form-group\">\n");
      out.write("						<label for=\"last_name\">Product Name</label> <input type=\"text\"\n");
      out.write("							placeholder=\"Enter Product Name\" name=\"name\" class=\"form-control\"\n");
      out.write("							id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6 form-group\">\n");
      out.write("						<label for=\"producttype\">Product Type</label> <select name=\"type\"\n");
      out.write("							id=\"producttype\" class=\"form-control\" required>\n");
      out.write("							<option value=\"mobile\">MOBILE</option>\n");
      out.write("							<option value=\"tv\">TV</option>\n");
      out.write("							<option value=\"camera\">CAMERA</option>\n");
      out.write("							<option value=\"laptop\">LAPTOP</option>\n");
      out.write("							<option value=\"tablet\">TABLET</option>\n");
      out.write("							<option value=\"speaker\">SPEAKER</option>\n");
      out.write("							<option value=\"other\">Some Other Appliances</option>\n");
      out.write("						</select>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"form-group\">\n");
      out.write("					<label for=\"last_name\">Product Description</label>\n");
      out.write("					<textarea name=\"info\" class=\"form-control\" id=\"last_name\" required></textarea>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6 form-group\">\n");
      out.write("						<label for=\"last_name\">Unit Price</label> <input type=\"number\"\n");
      out.write("							placeholder=\"Enter Unit Price\" name=\"price\" class=\"form-control\"\n");
      out.write("							id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6 form-group\">\n");
      out.write("						<label for=\"last_name\">Stock Quantity</label> <input type=\"number\"\n");
      out.write("							placeholder=\"Enter Stock Quantity\" name=\"quantity\"\n");
      out.write("							class=\"form-control\" id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div>\n");
      out.write("					<div class=\"col-md-12 form-group\">\n");
      out.write("						<label for=\"last_name\">Product Image</label> <input type=\"file\"\n");
      out.write("							placeholder=\"Select Image\" name=\"image\" class=\"form-control\"\n");
      out.write("							id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-6 text-center\" style=\"margin-bottom: 2px;\">\n");
      out.write("						<button type=\"reset\" class=\"btn btn-danger\">Reset</button>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-md-6 text-center\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">Add Product</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Shoping Center</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\n");
      out.write("	<!-- Start the footer Contacts -->\n");
      out.write("	<!-- <a name=\"contact\"></a> -->\n");
      out.write("	<div class=\"container-fluid\"\n");
      out.write("		style=\"background-color: #454545; color: white; margin-top: 200px;\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h3 class=\"text-center\">Contact</h3>\n");
      out.write("			<p class=\"text-center\">\n");
      out.write("				<em>We love our fans!</em>\n");
      out.write("			</p>\n");
      out.write("			<div class=\"row test\">\n");
      out.write("				<div class=\"col-md-4\">\n");
      out.write("					<p>Fan? Drop a note.</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-map-marker\"></span>Bitter Code\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-phone\"></span>Phone: +91\n");
      out.write("						1515151515\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-envelope\"></span>Email:\n");
      out.write("						thebittercode@gmail.com\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-copyright-mark\"></span>\n");
      out.write("						BitterCode - 2023\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-8\">\n");
      out.write("					<form action=\"fansMessage\" method=\"post\">\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-sm-6 form-group\">\n");
      out.write("								<input class=\"form-control\" id=\"name\" name=\"name\"\n");
      out.write("									placeholder=\"Name\" type=\"text\" required>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-sm-6 form-group\">\n");
      out.write("								<input class=\"form-control\" id=\"email\" name=\"email\"\n");
      out.write("									placeholder=\"Email\" type=\"email\" required>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<textarea class=\"form-control\" id=\"comments\" name=\"comments\"\n");
      out.write("							placeholder=\"Comment\" rows=\"5\" required></textarea>\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-md-12 form-group\">\n");
      out.write("								<button class=\"btn pull-right\" type=\"submit\">Send</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- End of Contact or about us -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
