/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-07-17 18:03:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.shashi.service.impl.*;
import com.shashi.service.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1752771139033L));
    _jspx_dependants.put("/footer.html", Long.valueOf(1752771139470L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.shashi.service.impl");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.shashi.service");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Login</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\n");
      out.write("\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Logout Header</title>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\n");
      out.write("	<!--Company Header Starting  -->\n");
      out.write("	<div class=\"container-fluid text-center\"\n");
      out.write("		style=\"margin-top: 45px; background-color: #33cc33; color: white; padding: 5px;\">\n");
      out.write("		<h2>Ellison Electronics</h2>\n");
      out.write("		<h6>We specialize in Electronics</h6>\n");
      out.write("		<form class=\"form-inline\" action=\"index.jsp\" method=\"get\">\n");
      out.write("			<div class=\"input-group\">\n");
      out.write("				<input type=\"text\" class=\"form-control\" size=\"50\" name=\"search\"\n");
      out.write("					placeholder=\"Search Items\" required>\n");
      out.write("				<div class=\"input-group-btn\">\n");
      out.write("					<input type=\"submit\" class=\"btn btn-danger\" value=\"Search\" />\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("		<p align=\"center\"\n");
      out.write("			style=\"color: blue; font-weight: bold; margin-top: 5px; margin-bottom: 5px;\"\n");
      out.write("			id=\"message\"></p>\n");
      out.write("	</div>\n");
      out.write("	<!-- Company Header Ending -->\n");
      out.write("\n");
      out.write("	");

	/* Checking the user credentials */
	String userType = (String) session.getAttribute("usertype");
	if (userType == null) { //LOGGED OUT
	
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Starting Navigation Bar -->\n");
      out.write("	<nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"navbar-header\">\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#myNavbar\">\n");
      out.write("					<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("						class=\"icon-bar\"></span>\n");
      out.write("				</button>\n");
      out.write("				<a class=\"navbar-brand\" href=\"index.jsp\"><span\n");
      out.write("					class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("				<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("					<li><a href=\"login.jsp\">Login</a></li>\n");
      out.write("					<li><a href=\"register.jsp\">Register</a></li>\n");
      out.write("					<li><a href=\"index.jsp\">Products</a></li>\n");
      out.write("					<li class=\"dropdown\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\n");
      out.write("					</a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li><a href=\"index.jsp?type=mobile\">Mobiles</a></li>\n");
      out.write("							<li><a href=\"index.jsp?type=tv\">TVs</a></li>\n");
      out.write("							<li><a href=\"index.jsp?type=laptop\">Laptops</a></li>\n");
      out.write("							<li><a href=\"index.jsp?type=camera\">Camera</a></li>\n");
      out.write("							<li><a href=\"index.jsp?type=speaker\">Speakers</a></li>\n");
      out.write("							<li><a href=\"index.jsp?type=tablet\">Tablets</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	");

	} else if ("customer".equalsIgnoreCase(userType)) { //CUSTOMER HEADER

	int notf = new CartServiceImpl().getCartCount((String) session.getAttribute("username"));
	
      out.write("\n");
      out.write("	<nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"navbar-header\">\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#myNavbar\">\n");
      out.write("					<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("						class=\"icon-bar\"></span>\n");
      out.write("				</button>\n");
      out.write("				<a class=\"navbar-brand\" href=\"userHome.jsp\"><span\n");
      out.write("					class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("				<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("					<li><a href=\"userHome.jsp\"><span\n");
      out.write("							class=\"glyphicon glyphicon-home\">Products</span></a></li>\n");
      out.write("					<li class=\"dropdown\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\n");
      out.write("					</a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li><a href=\"userHome.jsp?type=mobile\">Mobiles</a></li>\n");
      out.write("							<li><a href=\"userHome.jsp?type=tv\">TV</a></li>\n");
      out.write("							<li><a href=\"userHome.jsp?type=laptop\">Laptops</a></li>\n");
      out.write("							<li><a href=\"userHome.jsp?type=camera\">Camera</a></li>\n");
      out.write("							<li><a href=\"userHome.jsp?type=speaker\">Speakers</a></li>\n");
      out.write("							<li><a href=\"userHome.jsp?type=tablet\">Tablets</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					");

					if (notf == 0) {
					
      out.write("\n");
      out.write("					<li><a href=\"cartDetails.jsp\"> <span\n");
      out.write("							class=\"glyphicon glyphicon-shopping-cart\"></span>Cart\n");
      out.write("					</a></li>\n");
      out.write("\n");
      out.write("					");

					} else {
					
      out.write("\n");
      out.write("					<li><a href=\"cartDetails.jsp\"\n");
      out.write("						style=\"margin: 0px; padding: 0px;\" id=\"mycart\"><i\n");
      out.write("							data-count=\"");
      out.print(notf);
      out.write("\"\n");
      out.write("							class=\"fa fa-shopping-cart fa-3x icon-white badge\"\n");
      out.write("							style=\"background-color: #333; margin: 0px; padding: 0px; padding-bottom: 0px; padding-top: 5px;\">\n");
      out.write("						</i></a></li>\n");
      out.write("					");

					}
					
      out.write("\n");
      out.write("					<li><a href=\"orderDetails.jsp\">Orders</a></li>\n");
      out.write("					<li><a href=\"userProfile.jsp\">Profile</a></li>\n");
      out.write("					<li><a href=\"./LogoutSrv\">Logout</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	");

	} else { //ADMIN HEADER
	
      out.write("\n");
      out.write("	<nav class=\"navbar navbar-default navbar-fixed-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"navbar-header\">\n");
      out.write("				<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("					data-target=\"#myNavbar\">\n");
      out.write("					<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("						class=\"icon-bar\"></span>\n");
      out.write("				</button>\n");
      out.write("				<a class=\"navbar-brand\" href=\"adminViewProduct.jsp\"><span\n");
      out.write("					class=\"glyphicon glyphicon-home\">&nbsp;</span>Shopping Center</a>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("				<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("					<li><a href=\"adminViewProduct.jsp\">Products</a></li>\n");
      out.write("					<li class=\"dropdown\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\">Category <span class=\"caret\"></span>\n");
      out.write("					</a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=mobile\">Mobiles</a></li>\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=tv\">Tvs</a></li>\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=laptop\">Laptops</a></li>\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=camera\">Camera</a></li>\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=speaker\">Speakers</a></li>\n");
      out.write("							<li><a href=\"adminViewProduct.jsp?type=tablet\">Tablets</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li><a href=\"adminStock.jsp\">Stock</a></li>\n");
      out.write("					<li><a href=\"shippedItems.jsp\">Shipped</a></li>\n");
      out.write("					<li><a href=\"unshippedItems.jsp\">Orders</a></li>\n");
      out.write("					<!-- <li><a href=\"\"> <span class=\"glyphicon glyphicon-shopping-cart\"></span>&nbsp;Cart</a></li> -->\n");
      out.write("					<li class=\"dropdown\"><a class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" href=\"#\">Update Items <span\n");
      out.write("							class=\"caret\"></span>\n");
      out.write("					</a>\n");
      out.write("						<ul class=\"dropdown-menu\">\n");
      out.write("							<li><a href=\"addProduct.jsp\">Add Product</a></li>\n");
      out.write("							<li><a href=\"removeProduct.jsp\">Remove Product</a></li>\n");
      out.write("							<li><a href=\"updateProductById.jsp\">Update Product</a></li>\n");
      out.write("						</ul></li>\n");
      out.write("					<li><a href=\"./LogoutSrv\">Logout</a></li>\n");
      out.write("\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	");

	}
	
      out.write("\n");
      out.write("	<!-- End of Navigation Bar -->\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write('\n');
      out.write('\n');
      out.write('	');

	String message = request.getParameter("message");
	
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"row\"\n");
      out.write("			style=\"margin-top: 5px; margin-left: 2px; margin-right: 2px;\">\n");
      out.write("			<form action=\"./LoginSrv\" method=\"post\"\n");
      out.write("				class=\"col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2\"\n");
      out.write("				style=\"border: 2px solid black; border-radius: 10px; background-color: #FFE5CC; padding: 10px;\">\n");
      out.write("				<div style=\"font-weight: bold;\" class=\"text-center\">\n");
      out.write("					<h2 style=\"color: green;\">Login Form</h2>\n");
      out.write("					");

					if (message != null) {
					
      out.write("\n");
      out.write("					<p style=\"color: blue;\">\n");
      out.write("						");
      out.print(message);
      out.write("\n");
      out.write("					</p>\n");
      out.write("					");

					}
					
      out.write("\n");
      out.write("				</div>\n");
      out.write("				<div></div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-12 form-group\">\n");
      out.write("						<label for=\"last_name\">Username</label> <input type=\"email\"\n");
      out.write("							placeholder=\"Enter Username\" name=\"username\" class=\"form-control\"\n");
      out.write("							id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-12 form-group\">\n");
      out.write("						<label for=\"last_name\">Password</label> <input type=\"password\"\n");
      out.write("							placeholder=\"Enter Password\" name=\"password\" class=\"form-control\"\n");
      out.write("							id=\"last_name\" required>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-12 form-group\">\n");
      out.write("						<label for=\"userrole\">Login As</label> <select name=\"usertype\"\n");
      out.write("							id=\"userrole\" class=\"form-control\" required>\n");
      out.write("							<option value=\"customer\" selected>CUSTOMER</option>\n");
      out.write("							<option value=\"admin\">ADMIN</option>\n");
      out.write("						</select>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-md-12 text-center\">\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\">Login</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Shoping Center</title>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/changes.css\">\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #E6F9E6;\">\n");
      out.write("	<!-- Start the footer Contacts -->\n");
      out.write("	<!-- <a name=\"contact\"></a> -->\n");
      out.write("	<div class=\"container-fluid\"\n");
      out.write("		style=\"background-color: #454545; color: white; margin-top: 200px;\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h3 class=\"text-center\">Contact</h3>\n");
      out.write("			<p class=\"text-center\">\n");
      out.write("				<em>We love our fans!</em>\n");
      out.write("			</p>\n");
      out.write("			<div class=\"row test\">\n");
      out.write("				<div class=\"col-md-4\">\n");
      out.write("					<p>Fan? Drop a note.</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-map-marker\"></span>Bitter Code\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-phone\"></span>Phone: +91\n");
      out.write("						1515151515\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-envelope\"></span>Email:\n");
      out.write("						thebittercode@gmail.com\n");
      out.write("					</p>\n");
      out.write("					<p>\n");
      out.write("						<span class=\"glyphicon glyphicon-copyright-mark\"></span>\n");
      out.write("						BitterCode - 2023\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-md-8\">\n");
      out.write("					<form action=\"fansMessage\" method=\"post\">\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-sm-6 form-group\">\n");
      out.write("								<input class=\"form-control\" id=\"name\" name=\"name\"\n");
      out.write("									placeholder=\"Name\" type=\"text\" required>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-sm-6 form-group\">\n");
      out.write("								<input class=\"form-control\" id=\"email\" name=\"email\"\n");
      out.write("									placeholder=\"Email\" type=\"email\" required>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<textarea class=\"form-control\" id=\"comments\" name=\"comments\"\n");
      out.write("							placeholder=\"Comment\" rows=\"5\" required></textarea>\n");
      out.write("						<div class=\"row\">\n");
      out.write("							<div class=\"col-md-12 form-group\">\n");
      out.write("								<button class=\"btn pull-right\" type=\"submit\">Send</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- End of Contact or about us -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
